#!/usr/bin/bash

pin_arr=(20 21 23 24) #각 gpio 핀번호 배열에 저장 
pin_count=3 #불이 켜질 순서를 저장하는 변수 1을 증가시키고 4모듈러연산을 위해 3에서 시작

for i in ${pin_arr[@]}; # 각 핀 셋팅
do
 	pinctrl set $i op; # 각 핀 아웃풋으로 설정
 	pinctrl set $i dl; # 각 핀 LOW로 설정
done

while true;  #계속해서 반복 
do
	pinctrl set ${pin_arr[$(( ($pin_count+1)%4)) ]} dh; #현재에 해당하는 핀에 불을 킴
	pinctrl set ${pin_arr[$((   $pin_count%4 ))  ]} dl; #현재 이전에 켜져있던 불을 끔

	pin_count=$(( ($pin_count+1)%4 )); #다음 led를 키기위해 1을 증가시키고 4개 led 순환을 위해 4모듈러 연산
    sleep 1; #1초 대기
done