#!/usr/bin/bash #/usr/bin/bash로 아래를 해석합니다.

pin_arr=(20 21 23 24) #각 gpio 핀번호 배열에 저장 

for i in ${pin_arr[@]}; # 각 pin_arr요소를  순서대로 i할당하며 반복
do
 	pinctrl set $i op; # 각 핀 아웃풋으로 설정
 	pinctrl set $i dl; # 각 핀 LOW로 설정
done

while true;  #계속해서 반복 
do
	for i in ${pin_arr[@]}; # 각 pin_arr요소를  순서대로 i할당하며 반복
	do
 		pinctrl set $i dh; # 해당 핀을 high로 설정
 		sleep 1 # 1초 대기
		pinctrl set $i dl; # 해당 핀 LOW로 설정
	done
done
